BEGIN begin'\n';
END end|(end'\n');
WHILE while' ''(';
DO ')'' 'do'\n';
OD od'\n';
IF if' ''(';
THEN ')'' 'then'\n';
ELSE else'\n';
FI fi'\n';
VARIABLE (end|a*)(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z)+;
INTEGER (('-'|1*)(1|2|3|4|5|6|7|8|9)(0|1|2|3|4|5|6|7|8|9)*)|0;
ASSIGN ' ''='' ';
OPERATOR ' '('+'|'-'|'*'|'>'|('=''='))' ';
NEWLINE '\n';
INDENTATION (' '|'	')+;
